

-- MySQL Script generated by MySQL Workbench
-- Sun Oct 18 03:21:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema faqosdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema faqosdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `faqosdb` DEFAULT CHARACTER SET utf8 ;
USE `faqosdb` ;

-- -----------------------------------------------------
-- Table `faqosdb`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faqosdb`.`role` ;

CREATE TABLE IF NOT EXISTS `faqosdb`.`role` (
  `id` INT(9) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `faqosdb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faqosdb`.`user` ;

CREATE TABLE IF NOT EXISTS `faqosdb`.`user` (
  `id` INT(9) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  `ip_adress` INT(11) NOT NULL,
  `role_id` INT(9) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `faqosdb`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `faqosdb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faqosdb`.`categories` ;

CREATE TABLE IF NOT EXISTS `faqosdb`.`categories` (
  `id` INT(9) NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NOT NULL,
  `contenu` VARCHAR(255) NOT NULL,
  `cover` VARCHAR(255) NOT NULL,
  `created_by` INT(11) NOT NULL,
  `created_at` DATE NOT NULL,
  `disabled_by` INT(11) NOT NULL,
  `disabled_at` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categories_user1_idx` (`created_by` ASC),
  INDEX `fk_categories_user2_idx` (`disabled_by` ASC),
  CONSTRAINT `fk_categories_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `faqosdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_user2`
    FOREIGN KEY (`disabled_by`)
    REFERENCES `faqosdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `faqosdb`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faqosdb`.`question` ;

CREATE TABLE IF NOT EXISTS `faqosdb`.`question` (
  `id` INT(9) NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NOT NULL,
  `contenu` VARCHAR(255) NOT NULL,
  `created_by` INT(11) NOT NULL,
  `created_at` DATE NOT NULL,
  `disabled_by` INT(11) NOT NULL,
  `disabled_at` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_question_user1_idx` (`created_by` ASC),
  INDEX `fk_question_user1_idx1` (`disabled_by` ASC),
  CONSTRAINT `fk_question_user`
    FOREIGN KEY (`created_by`)
    REFERENCES `faqosdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_user1`
    FOREIGN KEY (`disabled_by`)
    REFERENCES `faqosdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `faqosdb`.`reponse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faqosdb`.`reponse` ;

CREATE TABLE IF NOT EXISTS `faqosdb`.`reponse` (
  `id` INT(9) NOT NULL AUTO_INCREMENT,
  `question_id` INT(9) NOT NULL,
  `contenu` VARCHAR(255) NOT NULL,
  `created_by` INT(11) NOT NULL,
  `created_at` DATE NOT NULL,
  `disabled_by` INT(11) NOT NULL,
  `disabled_at` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reponse_question_idx` (`question_id` ASC),
  INDEX `fk_reponse_user1_idx` (`created_by` ASC),
  INDEX `fk_reponse_user2_idx` (`disabled_by` ASC),
  CONSTRAINT `fk_reponse_question`
    FOREIGN KEY (`question_id`)
    REFERENCES `faqosdb`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reponse_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `faqosdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reponse_user2`
    FOREIGN KEY (`disabled_by`)
    REFERENCES `faqosdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `faqosdb`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faqosdb`.`tags` ;

CREATE TABLE IF NOT EXISTS `faqosdb`.`tags` (
  `id` INT(9) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `created_by` INT(11) NOT NULL,
  `created_at` DATE NOT NULL,
  `disabled_by` INT(11) NOT NULL,
  `disabled_at` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tags_user1_idx` (`created_by` ASC),
  INDEX `fk_tags_user2_idx` (`disabled_by` ASC),
  CONSTRAINT `fk_tags_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `faqosdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags_user2`
    FOREIGN KEY (`disabled_by`)
    REFERENCES `faqosdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `faqosdb`.`vote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faqosdb`.`vote` ;

CREATE TABLE IF NOT EXISTS `faqosdb`.`vote` (
  `vote_id` INT(9) NOT NULL AUTO_INCREMENT,
  `vote_value` INT(1) NOT NULL,
  `reponse_id` INT(11) NOT NULL,
  `ip_adress` INT(11) NOT NULL,
  `user_id` INT(9) NOT NULL,
  PRIMARY KEY (`vote_id`),
  INDEX `fk_vote_reponse1_idx` (`reponse_id` ASC),
  INDEX `fk_vote_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_vote_reponse1`
    FOREIGN KEY (`reponse_id`)
    REFERENCES `faqosdb`.`reponse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vote_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `faqosdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `faqosdb`.`question_has_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faqosdb`.`question_has_tags` ;

CREATE TABLE IF NOT EXISTS `faqosdb`.`question_has_tags` (
  `question_id` INT(9) NOT NULL,
  `tags_id` INT(9) NOT NULL,
  PRIMARY KEY (`question_id`, `tags_id`),
  INDEX `fk_question_has_tags_tags1_idx` (`tags_id` ASC),
  INDEX `fk_question_has_tags_question1_idx` (`question_id` ASC),
  CONSTRAINT `fk_question_has_tags_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `faqosdb`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_has_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `faqosdb`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `faqosdb`.`question_has_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faqosdb`.`question_has_categories` ;

CREATE TABLE IF NOT EXISTS `faqosdb`.`question_has_categories` (
  `question_id` INT(9) NOT NULL,
  `categories_id` INT(9) NOT NULL,
  PRIMARY KEY (`question_id`, `categories_id`),
  INDEX `fk_question_has_categories_categories1_idx` (`categories_id` ASC),
  INDEX `fk_question_has_categories_question1_idx` (`question_id` ASC),
  CONSTRAINT `fk_question_has_categories_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `faqosdb`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_has_categories_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `faqosdb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
